Feature/11889 layout home page
occitech/fcl-blogshop pull request #5
Opened 2018-04-26 13:20 UTC by erochOnGit

2018-04-26 15:25 UTC, milkae commented on src/web/theme/modules/ProductList/ProductList.js
> +      <ProductItem title="<span>Don’t just buy</span><span class='bold'> a product,</span><span> buy</span><span class='primary'> a complete experience!</span>" />
So it's not a ProductItem

2018-04-27 06:53 UTC, real34 approved these changes

2018-04-27 06:53 UTC, real34 commented on src/web/theme/ui/organisms/Media/Media.scss
> +    &.product-item-title {
I think this component declaration should be extracted in its own component, with its BEM namespace… and more expressive naming conventions.
It does not really belong here, and the current implementation has room for improvements.

2018-04-27 06:55 UTC, real34 requested changes
(sorry, I misclicked for my previous review… I agree that this fake `ProductItem` is a bad smell)

2018-04-30 13:35 UTC, merged